version: '3.8'

services:
    mongodb:
        image: mongo:latest
        environment:
            MONGO_DB: face-recognition
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: admin
        ports:
            - 27017:27017
        volumes:
            - mongodb:/data/db

    fastapi:
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - .env
        ports:
            - 8000:8000
        depends_on: 
            - mongodb

volumes:
    mongodb:
