version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: your_root_username
      MONGO_INITDB_ROOT_PASSWORD: your_root_password
    ports:
      - "27017:27017"
