version: "3.8"
services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: "mongodb://mongodb:27017"

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
